services:
  app:
    build:
      context: .
      args:
        NODE_VERSION: "20.18.0"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
