# fly.toml app configuration file generated for devuniversity-challenge-empty-lake-4316 on 2025-02-03T20:35:56-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'devuniversity-challenge-empty-lake-4316'
primary_region = 'eze'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
